---
title: Bill Perry Law
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: https://www.billperrylaw.com
baseurl: 
exclude:
- CNAME
